### ISSUE TITLE
Cannot create effect in non-reactive scope.

### ISSUE THREAD

**Issue by blinxess** [centau/vide#12]
<h2>I get this warning or error whenever I try and use **effect** in my return function for my component.</h2>

```lua
return function (props: {
    Title: string,
    Open: boolean,

    Position: UDim2,
})
    local panel
    local size = source(35)

    effect(function()
        if not panel then return end

        panel.Size = UDim2.fromOffset(250, size())
    end, size)

    panel = create "Frame" { ... }
```

**Comment by littensy** [comment]
Is your component being created within a `root()` or [`mount()`](https://centau.github.io/vide/api/creation.html#mount) call? A 'root scope' created by these functions needs to be present for functions like `effect()` to work.

**Comment by blinxess** [comment]
No it wasn't, I was having issues with mount. But I will try it

**Comment by littensy** [comment]
> No it wasn't, I was having issues with mount. But I will try it

Did that get resolved?

**Comment by blinxess** [comment]
> > No it wasn't, I was having issues with mount. But I will try it
> 
> Did that get resolved?

It did, thanks!
