### ISSUE TITLE
Spring when underdamped results in weird animations

### ISSUE THREAD

**Issue by AnUnderratedPerson** [centau/vide#4]
When `damping_ratio` is adjusted and set to 0.5, this results in weird positional values as shown below in the video:

https://github.com/centau/vide/assets/75079031/56dcd3e8-7577-4918-af7d-c5fe8d49c81a

> Note: This does not happen when the spring is critically damped.

Code:
```lua
local Positional = Source(UDim2.fromScale(0, 0))

local Frame = Create "Frame" {
	Layout = {
		AnchorPoint = Vector2.new(0.5, 0.5),
		Size = UDim2.fromScale(0.1, 0.1),
		Position = Spring(Positional, 5, 0.5),
	},

	Parent = MainInterface
}

while (task.wait(6)) do
	local xRand = math.random(2, 8) / 10
	local yRand = math.random(2, 8) / 10

	Positional(UDim2.fromScale(xRand, yRand))
end
```

**Comment by centau** [comment]
This looks like an issue with how Vide detects when a spring has finished, then setting it to its target position

Thanks for report
