### ISSUE TITLE
Add `indexes`/`values` API for dynamic keys and values

### ISSUE THREAD

**Issue by littensy** [centau/vide#7]
There are some cases where you want to render a list of entities whose keys _and_ values may change. If you have a table source `Array<Item>`, and want to assign a component for each item id without re-creating the component when the item or index changes, you'd map it to a new table of type `Map<string, Item>` like so:

```lua
local itemsById = derive(function()
    local map: Map<string, Item> = {}
    for _, item in items do
        map[item.id] = item
    end
    return map
end)

return indexes(itemsById, function(item: () -> Item, id: string)
    -- ...
end)
```

This approach works fine, but you lose the original order of the item in the process. It's tedious to keep this in mind when rendering lists where both keys _and_ values change over time.

Storing an array of sources and using `vide.values` instead is also an alternative, but it is not the best option in some cases, especially when using a separate library for state management.

### Proposal

I think Vide could have a new table source API, `vide.entries()`, with an additional argument for assigning a unique identifier to an entity. This way, both the key and value passed to `transform` are sources, allowing the component to react to any change in order and state without being re-created.

```lua
return entries(items, function(item: Item, index: number)
    return item.id
end, function(item: () -> Item, index: () -> number, id: string)
    -- ...
end)
```

This is similar to [the `key` prop](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key) from React, which allows you to render components with the latest item index and value for as long as their `key` prop stays the same. Components are only unmounted when the data associated with that specific `key` is removed from the table.

**Comment by centau** [comment]
Hi Littensy, do you still think this should be added to vide?

I see the usecase for it but I am wondering if this is common enough to justify adding to the API. Vide is a library I expect users to write their own utilities for, using the building blocks vide provides such as `effect()` and `cleanup()`. Things I consider is how common it is and how difficult it is to implement yourself.

A good example of this I think is the RxJS library, if you are familiar with that, I think vide's API would start to look like that if I added utilities for more niche usecases. I don't think this is definitely a bad thing, but I am looking for thoughts on it.

**Comment by littensy** [comment]
@centau Generally, I haven't had a use case in my own projects. Even if I did, manually mapping an object in a derived source is a viable alternative to this API. I don't think it's necessary.
